---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchbase-cluster
  namespace: couchbase-cluster
  labels:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
spec:
  replicas: 3
  serviceName: couchbase-cluster-svc
  selector:
    matchLabels:
      app.kubernetes.io/component: couchbase-server
      app.kubernetes.io/name: couchbase-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/component: couchbase-server
        app.kubernetes.io/name: couchbase-cluster
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: couchbase-cluster
        image: docker.io/justdomepaul/couchbase-cluster:latest
        ports:
        - name: couchbase-port
          containerPort: 8091
        volumeMounts:
        - name: couchbase-cluster-pvc
          mountPath: /opt/couchbase/var
        env:
        - name: COUCHBASE_MASTER
          value: "couchbase-cluster-0.couchbase-cluster-svc.couchbase-cluster.svc.cluster.local"
        - name: AUTO_REBALANCE
          value: "true"
        - name: CLUSTER_CUSTOM_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchbase-administrator
              key: username
        - name: CLUSTER_CUSTOM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchbase-administrator
              key: password
  volumeClaimTemplates:
  - metadata:
      name: couchbase-cluster-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: sc-couchbase
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-cluster-svc
  namespace: couchbase-cluster
  labels:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
spec:
  ports:
  - name: couchbase
    port: 8091
  # *.couchbase.default.svc.cluster.local
  clusterIP: None
  selector:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-cluster-ui
  namespace: couchbase-cluster
  labels:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-ui
spec:
  ports:
  - name: couchbase-ui
    port: 8091
  selector:
    app.kubernetes.io/component: couchbase-server
    app.kubernetes.io/name: couchbase-cluster
  sessionAffinity: ClientIP
  type: LoadBalancer
